name: Build & Publish

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [main]
  workflow_dispatch: # Manually run the workflow

jobs:
  next-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: create env file
        run: echo "${{ secrets.ENV_VARS }}" >> .env

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Docker Images
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: .Dockerfile
          platform: linux/arm64/v8,linux/amd6
          platforms: linux/arm64/v8,linux/amd6
          push: true
          tags: shinhyeok/dobda-client:latest
